// Zaimu — Realistic Demo Data
// Japanese institutional investor: Sanyo Capital Holdings
// Portfolio: North American + Australian Office & Industrial Assets

export const MOCK_ORG = {
  id: "org_sanyo",
  name: "Sanyo Capital Holdings",
  nameJa: "三洋キャピタルホールディングス",
  type: "CORPORATE",
  country: "JP",
  currency: "JPY",
};

export const MOCK_USER = {
  id: "user_yamamoto",
  name: "Kenji Yamamoto",
  nameJa: "山本 賢二",
  email: "k.yamamoto@sanyocapital.co.jp",
  role: "PORTFOLIO_MANAGER",
  language: "ja",
};

export const MOCK_FX_RATES = {
  USDJPY: 155.40,
  AUDJPY: 98.20,
  GBPJPY: 196.30,
  EURJPY: 168.10,
};

export const MOCK_ASSETS = [
  {
    id: "ast_001",
    name: "1 Market Plaza",
    nameJa: "1マーケットプラザ",
    assetType: "OFFICE",
    status: "ACTIVE",
    country: "US",
    city: "San Francisco, CA",
    address: "1 Market Plaza, San Francisco, CA 94105",
    totalArea: 45200,
    areaUnit: "sqft",
    acquisitionDate: "2021-03-15",
    acquisitionCost: 87500000,
    currency: "USD",
    currentValuation: 94200000,
    lastValuationDate: "2025-12-31",
    occupancyRate: 91.5,
    operationalScore: 84,
    reportingScore: 92,
    covenantStatus: "COMPLIANT",
    refinancingDate: "2027-03-15",
    portfolioId: "ptf_001",
  },
  {
    id: "ast_002",
    name: "Collins Square Tower 5",
    nameJa: "コリンズスクエアタワー5",
    assetType: "OFFICE",
    status: "ACTIVE",
    country: "AU",
    city: "Melbourne, VIC",
    address: "Tower 5, 727 Collins St, Melbourne VIC 3000",
    totalArea: 38400,
    areaUnit: "sqm",
    acquisitionDate: "2020-08-30",
    acquisitionCost: 142000000,
    currency: "AUD",
    currentValuation: 155000000,
    lastValuationDate: "2025-12-31",
    occupancyRate: 96.0,
    operationalScore: 91,
    reportingScore: 88,
    covenantStatus: "COMPLIANT",
    refinancingDate: "2026-08-30",
    portfolioId: "ptf_001",
  },
  {
    id: "ast_003",
    name: "Houston Distribution Hub",
    nameJa: "ヒューストン物流ハブ",
    assetType: "LOGISTICS",
    status: "ACTIVE",
    country: "US",
    city: "Houston, TX",
    address: "8500 Railwood Dr, Houston, TX 77078",
    totalArea: 285000,
    areaUnit: "sqft",
    acquisitionDate: "2022-11-01",
    acquisitionCost: 68000000,
    currency: "USD",
    currentValuation: 75500000,
    lastValuationDate: "2025-12-31",
    occupancyRate: 100,
    operationalScore: 96,
    reportingScore: 79,
    covenantStatus: "WATCH",
    refinancingDate: "2027-11-01",
    portfolioId: "ptf_001",
  },
  {
    id: "ast_004",
    name: "Canary Wharf Office Centre",
    nameJa: "カナリーワーフ・オフィスセンター",
    assetType: "OFFICE",
    status: "REFINANCING",
    country: "GB",
    city: "London",
    address: "25 Bank St, Canary Wharf, London E14 5JP",
    totalArea: 52000,
    areaUnit: "sqm",
    acquisitionDate: "2019-06-01",
    acquisitionCost: 210000000,
    currency: "GBP",
    currentValuation: 195000000,
    lastValuationDate: "2025-09-30",
    occupancyRate: 78.5,
    operationalScore: 62,
    reportingScore: 71,
    covenantStatus: "WATCH",
    refinancingDate: "2026-06-01",
    portfolioId: "ptf_001",
  },
  {
    id: "ast_005",
    name: "Sydney Olympic Park Industrial",
    nameJa: "シドニーオリンピックパーク工業地区",
    assetType: "INDUSTRIAL",
    status: "ACTIVE",
    country: "AU",
    city: "Sydney, NSW",
    address: "Olympic Blvd, Sydney Olympic Park NSW 2127",
    totalArea: 48000,
    areaUnit: "sqm",
    acquisitionDate: "2023-02-28",
    acquisitionCost: 98000000,
    currency: "AUD",
    currentValuation: 103500000,
    lastValuationDate: "2025-12-31",
    occupancyRate: 100,
    operationalScore: 98,
    reportingScore: 95,
    covenantStatus: "COMPLIANT",
    refinancingDate: "2028-02-28",
    portfolioId: "ptf_001",
  },
];

export const MOCK_LOANS = [
  {
    id: "loan_001",
    assetId: "ast_001",
    lenderName: "Wells Fargo Bank",
    loanType: "SENIOR",
    currency: "USD",
    originalBalance: 52500000,
    currentBalance: 49800000,
    interestRate: 0.0625,
    rateType: "FLOATING",
    margin: 0.0185,
    benchmark: "SOFR",
    originationDate: "2021-03-15",
    maturityDate: "2027-03-15",
    ltv: 52.9,
    dscr: 1.42,
    status: "CURRENT",
  },
  {
    id: "loan_002",
    assetId: "ast_002",
    lenderName: "ANZ Banking Group",
    loanType: "SENIOR",
    currency: "AUD",
    originalBalance: 85200000,
    currentBalance: 81400000,
    interestRate: 0.0592,
    rateType: "FLOATING",
    margin: 0.0175,
    benchmark: "BBSY",
    originationDate: "2020-08-30",
    maturityDate: "2026-08-30",
    ltv: 52.5,
    dscr: 1.58,
    status: "CURRENT",
  },
  {
    id: "loan_003",
    assetId: "ast_003",
    lenderName: "JPMorgan Chase",
    loanType: "SENIOR",
    currency: "USD",
    originalBalance: 40800000,
    currentBalance: 38900000,
    interestRate: 0.0640,
    rateType: "FIXED",
    margin: null,
    benchmark: null,
    originationDate: "2022-11-01",
    maturityDate: "2027-11-01",
    ltv: 51.5,
    dscr: 1.31,
    status: "WATCH",
  },
  {
    id: "loan_004",
    assetId: "ast_004",
    lenderName: "HSBC UK",
    loanType: "SENIOR",
    currency: "GBP",
    originalBalance: 126000000,
    currentBalance: 122500000,
    interestRate: 0.0728,
    rateType: "FLOATING",
    margin: 0.0215,
    benchmark: "SONIA",
    originationDate: "2019-06-01",
    maturityDate: "2026-06-01",
    ltv: 62.8,
    dscr: 1.12,
    status: "WATCH",
  },
  {
    id: "loan_005",
    assetId: "ast_005",
    lenderName: "Commonwealth Bank of Australia",
    loanType: "SENIOR",
    currency: "AUD",
    originalBalance: 58800000,
    currentBalance: 57100000,
    interestRate: 0.0578,
    rateType: "FLOATING",
    margin: 0.0160,
    benchmark: "BBSY",
    originationDate: "2023-02-28",
    maturityDate: "2028-02-28",
    ltv: 55.2,
    dscr: 2.10,
    status: "CURRENT",
  },
];

export const MOCK_COVENANTS = [
  { loanId: "loan_001", covenantType: "LTV", description: "Loan-to-Value Ratio", threshold: "≤ 65%", currentValue: "52.9%", status: "COMPLIANT", testFreq: "Quarterly", nextTestDate: "2026-06-30" },
  { loanId: "loan_001", covenantType: "DSCR", description: "Debt Service Coverage", threshold: "≥ 1.25x", currentValue: "1.42x", status: "COMPLIANT", testFreq: "Semi-annual", nextTestDate: "2026-06-30" },
  { loanId: "loan_003", covenantType: "DSCR", description: "Debt Service Coverage", threshold: "≥ 1.35x", currentValue: "1.31x", status: "WATCH", testFreq: "Quarterly", nextTestDate: "2026-06-30" },
  { loanId: "loan_003", covenantType: "OCCUPANCY", description: "Minimum Occupancy Rate", threshold: "≥ 90%", currentValue: "100%", status: "COMPLIANT", testFreq: "Monthly", nextTestDate: "2026-06-30" },
  { loanId: "loan_004", covenantType: "LTV", description: "Loan-to-Value Ratio", threshold: "≤ 60%", currentValue: "62.8%", status: "WATCH", testFreq: "Quarterly", nextTestDate: "2026-06-30" },
  { loanId: "loan_004", covenantType: "DSCR", description: "Debt Service Coverage", threshold: "≥ 1.30x", currentValue: "1.12x", status: "BREACH", testFreq: "Quarterly", nextTestDate: "2026-06-30" },
  { loanId: "loan_004", covenantType: "ICR", description: "Interest Coverage Ratio", threshold: "≥ 1.50x", currentValue: "1.38x", status: "BREACH", testFreq: "Quarterly", nextTestDate: "2026-06-30" },
];

export const MOCK_LEASES = [
  {
    id: "lease_001",
    assetId: "ast_001",
    tenantName: "Salesforce Inc.",
    floor: "Floors 12–18",
    area: 22400,
    areaUnit: "sqft",
    currency: "USD",
    baseRent: 95,
    rentFrequency: "MONTHLY_PSF",
    leaseStart: "2021-06-01",
    leaseEnd: "2028-05-31",
    breakDate: null,
    renewalWindow: "2027-12-01",
    status: "ACTIVE",
  },
  {
    id: "lease_002",
    assetId: "ast_001",
    tenantName: "Goldman Sachs",
    floor: "Floors 8–11",
    area: 14800,
    areaUnit: "sqft",
    currency: "USD",
    baseRent: 92,
    rentFrequency: "MONTHLY_PSF",
    leaseStart: "2020-09-01",
    leaseEnd: "2026-08-31",
    breakDate: "2026-02-28",
    renewalWindow: "2025-11-01",
    status: "ACTIVE",
  },
  {
    id: "lease_003",
    assetId: "ast_002",
    tenantName: "National Australia Bank",
    floor: "Floors 22–38",
    area: 28600,
    areaUnit: "sqm",
    currency: "AUD",
    baseRent: 620,
    rentFrequency: "ANNUAL_PSM",
    leaseStart: "2020-10-01",
    leaseEnd: "2030-09-30",
    breakDate: null,
    renewalWindow: "2029-04-01",
    status: "ACTIVE",
  },
  {
    id: "lease_004",
    assetId: "ast_003",
    tenantName: "Amazon Logistics",
    floor: "Full Building",
    area: 285000,
    areaUnit: "sqft",
    currency: "USD",
    baseRent: 8.50,
    rentFrequency: "ANNUAL_PSF",
    leaseStart: "2022-11-15",
    leaseEnd: "2032-11-14",
    breakDate: null,
    renewalWindow: "2031-05-01",
    status: "ACTIVE",
  },
  {
    id: "lease_005",
    assetId: "ast_004",
    tenantName: "Barclays Capital",
    floor: "Floors 5–14",
    area: 24500,
    areaUnit: "sqm",
    currency: "GBP",
    baseRent: 58,
    rentFrequency: "ANNUAL_PSM",
    leaseStart: "2019-09-01",
    leaseEnd: "2026-08-31",
    breakDate: "2026-02-28",
    renewalWindow: "2025-12-01",
    status: "ACTIVE",
  },
  {
    id: "lease_006",
    assetId: "ast_004",
    tenantName: "Morgan Stanley",
    floor: "Floors 1–4",
    area: 8200,
    areaUnit: "sqm",
    currency: "GBP",
    baseRent: 55,
    rentFrequency: "ANNUAL_PSM",
    leaseStart: "2021-01-01",
    leaseEnd: "2025-12-31",
    breakDate: null,
    renewalWindow: "2025-10-01",
    status: "NOTICE_GIVEN",
  },
];

export const MOCK_ALERTS = [
  {
    id: "alrt_001",
    assetId: "ast_004",
    alertType: "COVENANT_BREACH",
    severity: "CRITICAL",
    title: "DSCR Covenant Breach — Canary Wharf",
    titleJa: "DSCRコベナンツ違反 — カナリーワーフ",
    message: "DSCR of 1.12x is below the minimum covenant threshold of 1.30x. Lender notification required within 5 business days.",
    messageJa: "DSCRが1.12倍であり、最低コベナンツ基準の1.30倍を下回っています。5営業日以内に貸主への通知が必要です。",
    triggeredAt: "2026-05-15T09:00:00Z",
    resolved: false,
  },
  {
    id: "alrt_002",
    assetId: "ast_004",
    alertType: "LOAN_MATURITY",
    severity: "HIGH",
    title: "Loan Maturity — 12 Months — Canary Wharf",
    titleJa: "ローン満期 — 12ヶ月 — カナリーワーフ",
    message: "HSBC senior loan of GBP 122.5M matures in June 2026. Refinancing strategy requires board approval by Q3 2025.",
    messageJa: "HSBCシニアローン1億2250万ポンドが2026年6月に満期を迎えます。リファイナンス戦略は2025年Q3までに取締役会の承認が必要です。",
    triggeredAt: "2026-05-01T09:00:00Z",
    resolved: false,
  },
  {
    id: "alrt_003",
    assetId: "ast_004",
    alertType: "LEASE_EXPIRY",
    severity: "HIGH",
    title: "Lease Expiry — Morgan Stanley — Dec 2025",
    titleJa: "リース期限 — モルガン・スタンレー — 2025年12月",
    message: "Morgan Stanley lease (8,200 sqm, GBP 451K/year) expires 31 Dec 2025. Tenant has served notice to vacate.",
    messageJa: "モルガン・スタンレーのリース（8,200㎡、年間45.1万ポンド）は2025年12月31日に終了します。テナントは退去通知を提出済みです。",
    triggeredAt: "2026-05-01T09:00:00Z",
    resolved: false,
  },
  {
    id: "alrt_004",
    assetId: "ast_003",
    alertType: "COVENANT_WATCH",
    severity: "MEDIUM",
    title: "DSCR Approaching Threshold — Houston Hub",
    titleJa: "DSCR閾値接近 — ヒューストンハブ",
    message: "DSCR of 1.31x is within 5% of the minimum covenant threshold of 1.35x. Monitoring required.",
    messageJa: "DSCRが1.31倍であり、最低コベナンツ基準の1.35倍の5%以内に迫っています。モニタリングが必要です。",
    triggeredAt: "2026-05-10T09:00:00Z",
    resolved: false,
  },
  {
    id: "alrt_005",
    assetId: "ast_002",
    alertType: "LOAN_MATURITY",
    severity: "MEDIUM",
    title: "Loan Maturity — 15 Months — Collins Square",
    titleJa: "ローン満期 — 15ヶ月 — コリンズスクエア",
    message: "ANZ senior loan of AUD 81.4M matures in August 2026. Early refinancing discussions recommended.",
    messageJa: "ANZシニアローン8140万豪ドルが2026年8月に満期を迎えます。早期リファイナンス協議を推奨します。",
    triggeredAt: "2026-05-01T09:00:00Z",
    resolved: false,
  },
];

export const MOCK_TASKS = [
  {
    id: "task_001",
    assetId: "ast_004",
    title: "Notify HSBC of DSCR covenant breach",
    titleJa: "HSBCへのDSCRコベナンツ違反通知",
    category: "LENDER_COMMUNICATION",
    priority: "CRITICAL",
    status: "OPEN",
    assigneeName: "Kenji Yamamoto",
    dueDate: "2026-05-22",
    createdAt: "2026-05-15",
  },
  {
    id: "task_002",
    assetId: "ast_004",
    title: "Engage refinancing adviser — Canary Wharf",
    titleJa: "リファイナンスアドバイザー起用 — カナリーワーフ",
    category: "REFINANCING",
    priority: "HIGH",
    status: "IN_PROGRESS",
    assigneeName: "Takeshi Mori",
    dueDate: "2026-06-30",
    createdAt: "2026-05-01",
  },
  {
    id: "task_003",
    assetId: "ast_004",
    title: "Re-marketing strategy for Morgan Stanley space",
    titleJa: "モルガン・スタンレースペース再テナント戦略",
    category: "LEASE_MANAGEMENT",
    priority: "HIGH",
    status: "OPEN",
    assigneeName: "Yuki Tanaka",
    dueDate: "2026-06-15",
    createdAt: "2026-05-05",
  },
  {
    id: "task_004",
    assetId: "ast_001",
    title: "Renew Goldman Sachs lease — negotiate terms",
    titleJa: "ゴールドマン・サックスリース更新 — 条件交渉",
    category: "LEASE_MANAGEMENT",
    priority: "HIGH",
    status: "IN_PROGRESS",
    assigneeName: "Kenji Yamamoto",
    dueDate: "2026-07-31",
    createdAt: "2026-04-15",
  },
  {
    id: "task_005",
    assetId: "ast_002",
    title: "Prepare refinancing memo — Collins Square",
    titleJa: "リファイナンスメモ作成 — コリンズスクエア",
    category: "BOARD_PREPARATION",
    priority: "MEDIUM",
    status: "OPEN",
    assigneeName: "Hiroshi Kato",
    dueDate: "2026-07-15",
    createdAt: "2026-05-10",
  },
  {
    id: "task_006",
    assetId: null,
    title: "Prepare June 2026 monthly board report",
    titleJa: "2026年6月月次取締役会報告書作成",
    category: "REPORTING",
    priority: "HIGH",
    status: "OPEN",
    assigneeName: "Kenji Yamamoto",
    dueDate: "2026-06-10",
    createdAt: "2026-05-20",
  },
  {
    id: "task_007",
    assetId: "ast_003",
    title: "Review DSCR trend analysis — Houston Hub",
    titleJa: "DSCRトレンド分析レビュー — ヒューストンハブ",
    category: "COVENANT",
    priority: "MEDIUM",
    status: "OPEN",
    assigneeName: "Hiroshi Kato",
    dueDate: "2026-06-30",
    createdAt: "2026-05-12",
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: "doc_001",
    assetId: "ast_004",
    name: "HSBC Senior Facility Agreement",
    nameJa: "HSBCシニアファシリティ契約書",
    docType: "LOAN_AGREEMENT",
    status: "EXTRACTED",
    fileSize: 2847392,
    uploadedAt: "2026-05-01",
    processedAt: "2026-05-01",
    aiSummary: "Senior secured facility of GBP 126M. Maturity June 2026. DSCR covenant of 1.30x tested quarterly. LTV covenant of 60%. Two active breach conditions identified. Lender cure period of 30 days from notification.",
    aiSummaryJa: "1億2600万ポンドのシニア担保融資。2026年6月満期。DSCRコベナンツ1.30倍（四半期テスト）。LTVコベナンツ60%。2件の有効な違反条件を確認。通知から30日間の貸主治癒期間。",
    tags: ["covenant-breach", "urgent", "refinancing"],
    expiresAt: null,
    effectiveDate: "2019-06-01",
    parties: ["HSBC UK", "Canary Wharf Holdings Ltd", "Sanyo Capital Holdings"],
  },
  {
    id: "doc_002",
    assetId: "ast_004",
    name: "Morgan Stanley Notice to Quit",
    nameJa: "モルガン・スタンレー退去通知",
    docType: "LEGAL_OPINION",
    status: "REVIEWED",
    fileSize: 184920,
    uploadedAt: "2026-04-28",
    processedAt: "2026-04-28",
    aiSummary: "Formal notice to quit served by Morgan Stanley for their 8,200 sqm tenancy. Effective date 31 December 2025. No break penalty applicable. Early access for dilapidations survey from 1 October 2025.",
    aiSummaryJa: "モルガン・スタンレーが8,200㎡のテナントとして退去通知を提出。有効日2025年12月31日。ブレイクペナルティ不適用。2025年10月1日から損耗調査の早期アクセス可能。",
    tags: ["lease-expiry", "vacancy"],
    expiresAt: "2025-12-31",
    effectiveDate: "2026-04-25",
    parties: ["Morgan Stanley International", "Canary Wharf Holdings Ltd"],
  },
  {
    id: "doc_003",
    assetId: "ast_001",
    name: "Q1 2026 PM Report — 1 Market Plaza",
    nameJa: "2026年Q1 PMレポート — 1マーケットプラザ",
    docType: "PM_REPORT",
    status: "EXTRACTED",
    fileSize: 892450,
    uploadedAt: "2026-04-10",
    processedAt: "2026-04-10",
    aiSummary: "Strong Q1 performance. GOI of USD 2.1M, NOI of USD 1.68M. Occupancy stable at 91.5%. HVAC maintenance completed USD 142K (within budget). Goldman Sachs renewal negotiations ongoing. No significant operational issues.",
    aiSummaryJa: "Q1は好調な実績。GOI 210万ドル、NOI 168万ドル。稼働率91.5%で安定。HVAC保守が14.2万ドルで完了（予算内）。ゴールドマン・サックス更新交渉中。重大な運用上の問題なし。",
    tags: ["pm-report", "quarterly"],
    expiresAt: null,
    effectiveDate: "2026-03-31",
    parties: ["CBRE Property Management", "1 Market Associates LLC"],
  },
  {
    id: "doc_004",
    assetId: "ast_002",
    name: "Collins Square Valuation Report",
    nameJa: "コリンズスクエア評価報告書",
    docType: "VALUATION_REPORT",
    status: "REVIEWED",
    fileSize: 3420100,
    uploadedAt: "2026-01-15",
    processedAt: "2026-01-16",
    aiSummary: "Independent valuation of AUD 155M (31 Dec 2025). Cap rate compressed to 5.4%. Strong NAB anchor tenancy. Passing rent 5.2% below market. Value-add opportunity on lease renewal in 2030.",
    aiSummaryJa: "独立評価額1億5500万豪ドル（2025年12月31日）。キャップレートが5.4%に圧縮。NABアンカーテナントが強固。実勢賃料は市場より5.2%低い。2030年のリース更新時にバリューアップの機会あり。",
    tags: ["valuation", "annual"],
    expiresAt: "2026-12-31",
    effectiveDate: "2025-12-31",
    parties: ["Colliers International", "Collins Square Holdings Pty Ltd"],
  },
];

export const MOCK_REPORTS = [
  {
    id: "rpt_001",
    title: "May 2026 Portfolio Board Report",
    titleJa: "2026年5月ポートフォリオ取締役会報告書",
    reportType: "MONTHLY_BOARD",
    period: "2026-05-01",
    status: "REVIEW",
    language: "ja",
    generatedAt: "2026-05-20",
    createdAt: "2026-05-19",
  },
  {
    id: "rpt_002",
    title: "Canary Wharf Refinancing Memo",
    titleJa: "カナリーワーフ・リファイナンスメモ",
    reportType: "REFINANCING_MEMO",
    period: "2026-05-01",
    status: "DRAFT",
    language: "ja",
    generatedAt: null,
    createdAt: "2026-05-15",
  },
  {
    id: "rpt_003",
    title: "Q1 2026 Covenant Compliance Report",
    titleJa: "2026年Q1コベナンツ・コンプライアンス報告書",
    reportType: "COVENANT_REPORT",
    period: "2026-03-31",
    status: "APPROVED",
    language: "ja",
    generatedAt: "2026-04-10",
    createdAt: "2026-04-08",
  },
  {
    id: "rpt_004",
    title: "April 2026 Portfolio Board Report",
    titleJa: "2026年4月ポートフォリオ取締役会報告書",
    reportType: "MONTHLY_BOARD",
    period: "2026-04-01",
    status: "PUBLISHED",
    language: "ja",
    generatedAt: "2026-04-20",
    createdAt: "2026-04-18",
  },
];

export const MOCK_MEMORIES = [
  {
    id: "mem_001",
    assetId: "ast_004",
    memoryType: "LENDER_DISCUSSION",
    title: "HSBC — Preliminary Covenant Cure Discussion",
    titleJa: "HSBC — 予備的コベナンツ治癒協議",
    content: "Call with HSBC relationship manager James Crawford (15 May 2026). HSBC indicated they would prefer a cure plan over immediate enforcement, subject to board-approved refinancing timeline being submitted within 30 days. Tone constructive but firm. HSBC stressed the importance of maintaining occupancy improvements as primary cure mechanism.",
    contentJa: "HSBCリレーションシップマネージャーのジェームズ・クロフォードとの電話（2026年5月15日）。HSBCは、30日以内に取締役会承認のリファイナンスタイムラインを提出することを条件として、即時執行よりも治癒計画を優先したいと示唆。トーンは建設的だが毅然としていた。HSBCは、主要な治癒メカニズムとして稼働率改善の維持の重要性を強調した。",
    importance: "CRITICAL",
    period: "2026-05-15",
    tags: ["hsbc", "covenant", "refinancing"],
  },
  {
    id: "mem_002",
    assetId: "ast_001",
    memoryType: "TENANT_DISCUSSION",
    title: "Goldman Sachs Renewal — Position as of May 2026",
    titleJa: "ゴールドマン・サックス更新 — 2026年5月時点の状況",
    content: "Goldman Sachs (GS) lease expires August 2026. GS real estate team indicated willingness to renew 3-year term at current rates subject to GBP 2.5M landlord-funded TI package and co-working fit-out on Floor 8. GS also requesting HVAC upgrade for Floors 9-11. Management view: TI package acceptable at USD 2.5M; HVAC upgrade cost (USD 380K) to be treated as value-add capex. Recommend board approval of renewal terms.",
    contentJa: "ゴールドマン・サックス（GS）のリースは2026年8月に終了。GS不動産チームは、250万ポンドのランドロード負担TIパッケージと8階のコワーキング内装工事を条件として、現行レートでの3年更新に意欲を示した。GSは9-11階のHVACアップグレードも要求。経営陣の見解：TIパッケージは250万ドルで受け入れ可能；HVACアップグレード費用（38万ドル）はバリューアップCapexとして処理。更新条件の取締役会承認を推奨。",
    importance: "HIGH",
    period: "2026-05-12",
    tags: ["goldman-sachs", "lease-renewal", "capex"],
  },
  {
    id: "mem_003",
    assetId: null,
    memoryType: "BOARD_DECISION",
    title: "FX Hedging Policy — Board Approval Apr 2026",
    titleJa: "為替ヘッジポリシー — 2026年4月取締役会決議",
    content: "Board approved revised FX hedging policy on 22 April 2026. Key decisions: (1) USD exposure to be hedged 50-80% on 12-month rolling basis. (2) GBP exposure to be hedged 70-100% given current volatility. (3) AUD exposure: hedge 30-50% given natural income offset from Japanese repatriation schedule. (4) Authorise treasury team to execute hedges up to JPY 5B without additional board approval. Effective immediately.",
    contentJa: "取締役会は2026年4月22日に改訂版為替ヘッジポリシーを承認。主要決定事項：（1）USDエクスポージャーは12ヶ月ローリングベースで50-80%ヘッジ。（2）GBPエクスポージャーは現在のボラティリティを考慮し70-100%ヘッジ。（3）AUDエクスポージャー：日本への送金スケジュールとの自然相殺を考慮し30-50%ヘッジ。（4）財務チームに追加取締役会承認なしで500億円までのヘッジ実行を授権。即時有効。",
    importance: "HIGH",
    period: "2026-04-22",
    tags: ["fx-hedging", "board-decision", "treasury"],
  },
];

// ─── Computed portfolio statistics ────────────────────────────────────────

export const PORTFOLIO_STATS = {
  totalAumUsd: 430000000,
  totalAumJpy: 66822000000,
  totalDebtUsd: 248200000,
  totalDebtJpy: 38527080000,
  averageLtv: 55.8,
  averageDscr: 1.51,
  portfolioOccupancy: 91.6,
  assetCount: 5,
  covenantBreaches: 2,
  covenantWatch: 3,
  openTasks: 7,
  criticalAlerts: 1,
  highAlerts: 2,
  reportsDue: 1,
  jurisdictionBreakdown: [
    { country: "US", pct: 38, aum: 163400000, currency: "USD" },
    { country: "AU", pct: 34, aum: 146500000, currency: "AUD" },
    { country: "GB", pct: 28, aum: 120500000, currency: "GBP" },
  ],
  assetTypeBreakdown: [
    { type: "OFFICE",      pct: 64, count: 3 },
    { type: "LOGISTICS",   pct: 18, count: 1 },
    { type: "INDUSTRIAL",  pct: 18, count: 1 },
  ],
};

export const FX_EXPOSURES = [
  { currency: "USD", grossExposure: 163400000, hedged: 81700000, hedgePct: 50, pnlJpy: -240000000 },
  { currency: "GBP", grossExposure: 120500000, hedged: 96400000, hedgePct: 80, pnlJpy: -890000000 },
  { currency: "AUD", grossExposure: 146500000, hedged: 43950000, hedgePct: 30, pnlJpy: 120000000 },
];
